refactor: 인프라 모듈 추가 및 ConfigImporter 추가
gallery-side-project/backend pull request #43
Opened 2024-11-22 09:55 UTC by sukjuhong

## Overview

인프라 모듈 추가해서 ElasticSearch 관련 코드 넣어놨습니다.
이제 Config는 해당 모듈 내에서 관리하고 application 단에서 가져와서 사용해주세요.
Domain 내의 JPAConfig와 QueryDslConfig는 domain 모듈이 따로 분리되어 있기 때문에 그냥 가져왔습니다.
> 도메인도 이런식으로 만들고 싶은데, 인프라와 도메인이 같은 단에 있어서 어떻게 설정해야할지 모르겟습니다. 의견 가능할까요?

### Related Issue
Issue Number : resolves #42

## Task Details

- 인프라 모듈 추가
- elasticsearch 인프라 내로 이동
- Importer 관련 구현
- api 내의 InfraConfig 생성

## Review Requirements
코드 자체는 동일하지만 OpenSearch가  설정이 잘 되는지, 잘 돌아가는지 테스트해주세요.

2024-11-25 11:10 UTC, mclub4 requested changes
다 좋은데 Document, Repository라는 성격이 Infra 모듈 성격이랑 안맞는 것 같습니다.

2024-11-25 11:10 UTC, mclub4 commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
Document도 Infra 모듈에 넣은거 같은데.... 이렇게하면 뭔가 모듈 성격에 안맞는 것 같에요. Document도 Entity랑 똑같은거에요 사실....

2024-11-25 12:42 UTC, sukjuhong commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
그렇다면 batch나 admin을 만들때도 domain을 참조할텐데, elasticsearch의 의존성이 들어가지 않나요?

2024-11-26 00:38 UTC, mclub4 commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
틀린말은 아니네요. 어쩔 수 없는 부분인가... 솔직히 그런데 Infra라는 모듈 네이밍에 Document가 적합하지 않은 것은 사실입니다.

2024-11-26 00:41 UTC, mclub4 commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
아니면 admin이랑 batch에서 elasticsearch 의존성을 exclude하는 것은 별로인가요?

2024-11-27 12:11 UTC, sukjuhong commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
그 방법도 괜찮을 것 같네요. 변경 원하시면 시일내로 해보겠습니다.

2024-11-27 12:13 UTC, sukjuhong commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
![image](https://github.com/user-attachments/assets/7e652e96-50e7-4413-aecb-11311929c26a)

사실 보내신 글에선 비동기나 JPA 조차도 인프라로 취급하길래.. 인프라의 개념이 중요할 것 같네요

2024-11-27 12:29 UTC, mclub4 commented on pofo-infra/src/main/java/org/pofo/infra/elasticsearch/document/TechStackAutoComplete.java
> +package org.pofo.infra.elasticsearch.document;
일단 합칩시다. 변경하기에는 여러모로 문제가 많을 것 같기도하네요

2024-11-27 12:30 UTC, mclub4 approved these changes
일단 이 부분은 추후 문제가 생기면 고쳐보도록 합시다. 지금은 합치는게 좋아보이네요.

2024-11-27 12:30 UTC, merged